apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Flask-App-EKS-Cluster-VPC
  region: us-east-1

vpc:
  id: vpc-05f6c545f76c4c382
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-011ed41265b821f90
      us-east-1b:
        id: subnet-008e4371a0eabe507
    private:
      us-east-1a:
        id: subnet-0c54f263c9b5c6a30
      us-east-1b:
        id: subnet-0e4523593a8371d0a

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true