apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: web
    interval: 5s