apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-replication-controller
spec:
  replicas: 2
  selector:
    app: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: karthik540/todoapp:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: mongodb-service
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"