apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-replication-controller
spec:
  replicas: 3
  selector:
    app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: karthik540/mongodb:latest
        ports:
        - containerPort: 27017