apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: all-pods-monitor
  labels:
    monitoring: my-prometheus-kube-prometh-operator
spec:
  podMetricsEndpoints:
  - port: metrics
    interval: 5s
  selector:
    matchLabels: {}
  namespaceSelector:
    matchNames:
    - default
    - my-namespace
